# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "gh-action"
    labels:
      - "gh-action"
      - "dependencies"
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "next"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "python"
    labels:
      - "python"
      - "dependencies"
