name: Run tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  nix:
    runs-on: docker
    container:
      image: nix
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Nix doctor
        run: nix doctor
      - name: Check flake
        run: nix flake check --all-systems
      - name: Build flake
        run: nix build --print-out-paths
      - name: Flake info
        run: nix flake info
  tests:
    runs-on: docker
    container:
      image: debian:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          #go-version: "stable"
          go-version-file: "go.mod"
          check-latest: true
      - name: Run Linter
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
      - name: Run tests
        run: make test
