name: Run tests

on:
  push:
    branches:
      - next
  workflow_dispatch:

jobs:
  tests:
    runs-on: docker
    container:
      image: debian:stable
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          #go-version: "stable"
          go-version-file: "go.mod"
          check-latest: true
      - name: Run tests
        run: make test

